services:

  plex:
    image: plexinc/pms-docker:1.40.1.8227-c0dd5a73e
    container_name: my_plex
    expose:
      - 32400
      - 33400
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ${MEDIA_Lenny}/Plex Media Server:/config/Library/Application Support/Plex Media Server
      - ${MEDIA_Lenny}:/media/Lenny
      - ${MEDIA_Famous}:/media/Famous
      - ${MEDIA_Lenny}/tmp:/tmp
    restart: unless-stopped
    network_mode: "host"
